//! Native V3 `completions` command — shell completion scripts.
//!
//! Source of truth: `v3/@claude-flow/cli/src/commands/completions.ts`. Emits the
//! bash/zsh/fish/powershell scripts and the overview help when no shell is given.
//! `pwsh` is an alias for `powershell`. Overview ANSI honors NO_COLOR / non-TTY,
//! matching the V3 output module's color gating.

use std::io::IsTerminal;

pub fn run_overview() -> u8 {
    print!("{}", overview());
    0
}

pub fn run(shell: &str) -> u8 {
    let script = match shell {
        "bash" => BASH,
        "zsh" => ZSH,
        "fish" => FISH,
        "powershell" => POWERSHELL,
        _ => return 1,
    };
    // output.writeln appends a trailing newline to the emitted script.
    println!("{script}");
    0
}

fn color_enabled() -> bool {
    std::env::var_os("NO_COLOR").is_none() && std::io::stdout().is_terminal()
}

// Mirrors completions.ts:523-555: bold/dim/highlight helpers, printList renders
// `  - <item>` per entry (output.ts list() default bullet).
fn overview() -> String {
    let c = color_enabled();
    let bold = |s: &str| {
        if c {
            format!("\x1b[1m{s}\x1b[0m")
        } else {
            s.to_string()
        }
    };
    let dim = |s: &str| {
        if c {
            format!("\x1b[2m{s}\x1b[0m")
        } else {
            s.to_string()
        }
    };
    let hi = |s: &str| {
        if c {
            format!("\x1b[36m{s}\x1b[0m")
        } else {
            s.to_string()
        }
    };
    let mut out = String::new();
    out.push('\n');
    out.push_str(&bold("Shell Completions"));
    out.push('\n');
    out.push('\n');
    out.push_str("Generate shell completion scripts for tab completion support.");
    out.push('\n');
    out.push('\n');
    out.push_str("Supported shells:");
    out.push('\n');
    // output.printList -> list() joins "  - <item>" with \n, then writeln adds trailing \n.
    let shells = [
        format!("{}       - Bash completion", hi("bash")),
        format!("{}        - Zsh completion", hi("zsh")),
        format!("{}       - Fish completion", hi("fish")),
        format!("{} - PowerShell completion", hi("powershell")),
    ];
    out.push_str(
        &shells
            .iter()
            .map(|s| format!("  - {s}"))
            .collect::<Vec<_>>()
            .join("\n"),
    );
    out.push('\n');
    out.push('\n');
    out.push_str("Installation:");
    out.push('\n');
    out.push('\n');
    out.push_str(&bold("Bash:"));
    out.push('\n');
    out.push_str(&dim(
        "  claude-flow completions bash > ~/.bash_completion.d/claude-flow",
    ));
    out.push('\n');
    out.push_str(&dim("  source ~/.bash_completion.d/claude-flow"));
    out.push('\n');
    out.push('\n');
    out.push_str(&bold("Zsh:"));
    out.push('\n');
    out.push_str(&dim("  mkdir -p ~/.zfunc"));
    out.push('\n');
    out.push_str(&dim(
        "  claude-flow completions zsh > ~/.zfunc/_claude-flow",
    ));
    out.push('\n');
    out.push_str(&dim(
        "  # Add to ~/.zshrc: fpath=(~/.zfunc $fpath); autoload -Uz compinit && compinit",
    ));
    out.push('\n');
    out.push('\n');
    out.push_str(&bold("Fish:"));
    out.push('\n');
    out.push_str(&dim(
        "  claude-flow completions fish > ~/.config/fish/completions/claude-flow.fish",
    ));
    out.push('\n');
    out.push('\n');
    out.push_str(&bold("PowerShell:"));
    out.push('\n');
    out.push_str(&dim("  claude-flow completions powershell >> $PROFILE"));
    out.push('\n');
    out
}

const BASH: &str = r#"# claude-flow bash completion
# Generated by claude-flow completions bash
# Add this to ~/.bashrc or ~/.bash_completion

_claude_flow_completions() {
    local cur prev words cword
    _init_completion -n : || return

    local commands="swarm agent task session config memory workflow hive-mind hooks daemon neural security performance providers plugins deployment claims embeddings doctor completions help version"

    # Subcommand completions
    local swarm_commands="init status scale destroy monitor optimize"
    local agent_commands="spawn terminate status list pool health update"
    local task_commands="create status list complete cancel"
    local memory_commands="store retrieve search list delete stats configure cleanup compress export import"
    local hive_mind_commands="init spawn status task join leave consensus broadcast memory optimize-memory shutdown"
    local hooks_commands="pre-edit post-edit pre-command post-command pre-task post-task route explain pretrain build-agents metrics transfer list intelligence"

    case "${words[1]}" in
        swarm)
            COMPREPLY=( $(compgen -W "${swarm_commands}" -- "${cur}") )
            return 0
            ;;
        agent)
            COMPREPLY=( $(compgen -W "${agent_commands}" -- "${cur}") )
            return 0
            ;;
        task)
            COMPREPLY=( $(compgen -W "${task_commands}" -- "${cur}") )
            return 0
            ;;
        memory)
            COMPREPLY=( $(compgen -W "${memory_commands}" -- "${cur}") )
            return 0
            ;;
        hive-mind|hive)
            COMPREPLY=( $(compgen -W "${hive_mind_commands}" -- "${cur}") )
            return 0
            ;;
        hooks)
            COMPREPLY=( $(compgen -W "${hooks_commands}" -- "${cur}") )
            return 0
            ;;
        neural)
            COMPREPLY=( $(compgen -W "train status patterns predict optimize" -- "${cur}") )
            return 0
            ;;
        security)
            COMPREPLY=( $(compgen -W "scan cve threats audit secrets" -- "${cur}") )
            return 0
            ;;
        performance)
            COMPREPLY=( $(compgen -W "benchmark profile metrics optimize bottleneck" -- "${cur}") )
            return 0
            ;;
        plugins)
            COMPREPLY=( $(compgen -W "list install uninstall toggle info create" -- "${cur}") )
            return 0
            ;;
        deployment|deploy)
            COMPREPLY=( $(compgen -W "deploy status rollback history environments logs" -- "${cur}") )
            return 0
            ;;
        claims)
            COMPREPLY=( $(compgen -W "list check grant revoke roles policies" -- "${cur}") )
            return 0
            ;;
        embeddings)
            COMPREPLY=( $(compgen -W "generate search compare collections index providers" -- "${cur}") )
            return 0
            ;;
        daemon)
            COMPREPLY=( $(compgen -W "start stop status trigger enable" -- "${cur}") )
            return 0
            ;;
        providers)
            COMPREPLY=( $(compgen -W "list configure test models usage" -- "${cur}") )
            return 0
            ;;
        doctor)
            COMPREPLY=( $(compgen -W "--fix --component --verbose" -- "${cur}") )
            return 0
            ;;
    esac

    if [[ ${cword} -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "${commands}" -- "${cur}") )
        return 0
    fi
}

complete -F _claude_flow_completions claude-flow
complete -F _claude_flow_completions npx\ @claude-flow/cli@v3alpha
"#;

const ZSH: &str = r#"#compdef claude-flow
# claude-flow zsh completion
# Generated by claude-flow completions zsh
# Add to ~/.zfunc/_claude-flow or ~/.zsh/completions/_claude-flow

_claude_flow() {
    local -a commands
    local -a subcommands

    commands=(
        'swarm:Multi-agent swarm orchestration'
        'agent:Agent lifecycle management'
        'task:Task creation and management'
        'session:Session management'
        'config:Configuration management'
        'memory:Memory operations with AgentDB'
        'workflow:Workflow automation'
        'hive-mind:Queen-led consensus coordination'
        'hooks:Self-learning automation hooks'
        'daemon:Background service management'
        'neural:Neural pattern training'
        'security:Security scanning and CVE detection'
        'performance:Performance profiling'
        'providers:AI provider management'
        'plugins:Plugin management'
        'deployment:Deployment management'
        'claims:Claims-based authorization'
        'embeddings:Vector embeddings'
        'doctor:System diagnostics'
        'completions:Shell completion scripts'
        'help:Show help'
        'version:Show version'
    )

    _arguments -C \
        '1: :->command' \
        '2: :->subcommand' \
        '*:: :->args' && return

    case $state in
        command)
            _describe -t commands 'claude-flow commands' commands
            ;;
        subcommand)
            case $words[2] in
                swarm)
                    subcommands=(
                        'init:Initialize swarm'
                        'status:Show swarm status'
                        'scale:Scale agent count'
                        'destroy:Shutdown swarm'
                        'monitor:Real-time monitoring'
                        'optimize:Optimize topology'
                    )
                    ;;
                agent)
                    subcommands=(
                        'spawn:Create new agent'
                        'terminate:Stop agent'
                        'status:Check agent status'
                        'list:List all agents'
                        'pool:Manage agent pool'
                        'health:Health check'
                        'update:Update agent config'
                    )
                    ;;
                task)
                    subcommands=(
                        'create:Create new task'
                        'status:Check task status'
                        'list:List all tasks'
                        'complete:Mark task complete'
                        'cancel:Cancel task'
                    )
                    ;;
                memory)
                    subcommands=(
                        'store:Store data'
                        'retrieve:Retrieve data'
                        'search:Semantic search'
                        'list:List entries'
                        'delete:Delete entry'
                        'stats:Show statistics'
                        'configure:Configure backend'
                        'cleanup:Clean stale data'
                        'compress:Compress storage'
                        'export:Export to file'
                        'import:Import from file'
                    )
                    ;;
                hive-mind|hive)
                    subcommands=(
                        'init:Initialize hive mind'
                        'spawn:Spawn worker agents'
                        'status:Show hive status'
                        'task:Submit task'
                        'join:Join agent to hive'
                        'leave:Remove agent'
                        'consensus:Consensus management'
                        'broadcast:Broadcast message'
                        'memory:Shared memory'
                        'optimize-memory:Optimize patterns'
                        'shutdown:Shutdown hive'
                    )
                    ;;
                hooks)
                    subcommands=(
                        'pre-edit:Before file editing'
                        'post-edit:After file editing'
                        'pre-command:Before command execution'
                        'post-command:After command execution'
                        'pre-task:Before task start'
                        'post-task:After task completion'
                        'route:Route task to agent'
                        'explain:Explain routing'
                        'pretrain:Bootstrap intelligence'
                        'build-agents:Generate agent configs'
                        'metrics:Show metrics'
                        'transfer:Transfer learning'
                        'list:List hooks'
                        'intelligence:Neural intelligence commands'
                    )
                    ;;
                neural)
                    subcommands=(
                        'train:Train neural patterns'
                        'status:Check neural status'
                        'patterns:Manage patterns'
                        'predict:Make predictions'
                        'optimize:Optimize models'
                    )
                    ;;
                security)
                    subcommands=(
                        'scan:Security scan'
                        'cve:CVE detection'
                        'threats:Threat modeling'
                        'audit:Security audit'
                        'secrets:Secrets scanning'
                    )
                    ;;
                performance)
                    subcommands=(
                        'benchmark:Run benchmarks'
                        'profile:Profile code'
                        'metrics:Show metrics'
                        'optimize:Optimize performance'
                        'bottleneck:Find bottlenecks'
                    )
                    ;;
                plugins)
                    subcommands=(
                        'list:List plugins'
                        'install:Install plugin'
                        'uninstall:Remove plugin'
                        'toggle:Enable/disable'
                        'info:Plugin details'
                        'create:Scaffold plugin'
                    )
                    ;;
                deployment|deploy)
                    subcommands=(
                        'deploy:Deploy to environment'
                        'status:Deployment status'
                        'rollback:Rollback version'
                        'history:Deployment history'
                        'environments:List environments'
                        'logs:View logs'
                    )
                    ;;
                claims)
                    subcommands=(
                        'list:List claims'
                        'check:Check permission'
                        'grant:Grant claim'
                        'revoke:Revoke claim'
                        'roles:Manage roles'
                        'policies:Manage policies'
                    )
                    ;;
                embeddings)
                    subcommands=(
                        'generate:Generate embeddings'
                        'search:Semantic search'
                        'compare:Compare vectors'
                        'collections:Manage collections'
                        'index:Index operations'
                        'providers:Embedding providers'
                    )
                    ;;
                daemon)
                    subcommands=(
                        'start:Start daemon'
                        'stop:Stop daemon'
                        'status:Daemon status'
                        'trigger:Trigger event'
                        'enable:Enable feature'
                    )
                    ;;
                providers)
                    subcommands=(
                        'list:List providers'
                        'configure:Configure provider'
                        'test:Test connection'
                        'models:Available models'
                        'usage:Usage statistics'
                    )
                    ;;
            esac
            _describe -t subcommands 'subcommands' subcommands
            ;;
    esac
}

_claude_flow "$@"
"#;

const FISH: &str = r#"# claude-flow fish completion
# Generated by claude-flow completions fish
# Save to ~/.config/fish/completions/claude-flow.fish

# Disable file completion by default
complete -c claude-flow -f

# Top-level commands
complete -c claude-flow -n "__fish_use_subcommand" -a "swarm"
complete -c claude-flow -n "__fish_use_subcommand" -a "agent"
complete -c claude-flow -n "__fish_use_subcommand" -a "task"
complete -c claude-flow -n "__fish_use_subcommand" -a "session"
complete -c claude-flow -n "__fish_use_subcommand" -a "config"
complete -c claude-flow -n "__fish_use_subcommand" -a "memory"
complete -c claude-flow -n "__fish_use_subcommand" -a "workflow"
complete -c claude-flow -n "__fish_use_subcommand" -a "hive-mind"
complete -c claude-flow -n "__fish_use_subcommand" -a "hooks"
complete -c claude-flow -n "__fish_use_subcommand" -a "daemon"
complete -c claude-flow -n "__fish_use_subcommand" -a "neural"
complete -c claude-flow -n "__fish_use_subcommand" -a "security"
complete -c claude-flow -n "__fish_use_subcommand" -a "performance"
complete -c claude-flow -n "__fish_use_subcommand" -a "providers"
complete -c claude-flow -n "__fish_use_subcommand" -a "plugins"
complete -c claude-flow -n "__fish_use_subcommand" -a "deployment"
complete -c claude-flow -n "__fish_use_subcommand" -a "claims"
complete -c claude-flow -n "__fish_use_subcommand" -a "embeddings"
complete -c claude-flow -n "__fish_use_subcommand" -a "doctor"
complete -c claude-flow -n "__fish_use_subcommand" -a "completions"
complete -c claude-flow -n "__fish_use_subcommand" -a "help"
complete -c claude-flow -n "__fish_use_subcommand" -a "version"

# Swarm subcommands
complete -c claude-flow -n "__fish_seen_subcommand_from swarm" -a "init"
complete -c claude-flow -n "__fish_seen_subcommand_from swarm" -a "status"
complete -c claude-flow -n "__fish_seen_subcommand_from swarm" -a "scale"
complete -c claude-flow -n "__fish_seen_subcommand_from swarm" -a "destroy"
complete -c claude-flow -n "__fish_seen_subcommand_from swarm" -a "monitor"
complete -c claude-flow -n "__fish_seen_subcommand_from swarm" -a "optimize"

# Agent subcommands
complete -c claude-flow -n "__fish_seen_subcommand_from agent" -a "spawn"
complete -c claude-flow -n "__fish_seen_subcommand_from agent" -a "terminate"
complete -c claude-flow -n "__fish_seen_subcommand_from agent" -a "status"
complete -c claude-flow -n "__fish_seen_subcommand_from agent" -a "list"
complete -c claude-flow -n "__fish_seen_subcommand_from agent" -a "pool"
complete -c claude-flow -n "__fish_seen_subcommand_from agent" -a "health"
complete -c claude-flow -n "__fish_seen_subcommand_from agent" -a "update"

# Task subcommands
complete -c claude-flow -n "__fish_seen_subcommand_from task" -a "create"
complete -c claude-flow -n "__fish_seen_subcommand_from task" -a "status"
complete -c claude-flow -n "__fish_seen_subcommand_from task" -a "list"
complete -c claude-flow -n "__fish_seen_subcommand_from task" -a "complete"
complete -c claude-flow -n "__fish_seen_subcommand_from task" -a "cancel"

# Memory subcommands
complete -c claude-flow -n "__fish_seen_subcommand_from memory" -a "store"
complete -c claude-flow -n "__fish_seen_subcommand_from memory" -a "retrieve"
complete -c claude-flow -n "__fish_seen_subcommand_from memory" -a "search"
complete -c claude-flow -n "__fish_seen_subcommand_from memory" -a "list"
complete -c claude-flow -n "__fish_seen_subcommand_from memory" -a "delete"
complete -c claude-flow -n "__fish_seen_subcommand_from memory" -a "stats"
complete -c claude-flow -n "__fish_seen_subcommand_from memory" -a "configure"
complete -c claude-flow -n "__fish_seen_subcommand_from memory" -a "cleanup"
complete -c claude-flow -n "__fish_seen_subcommand_from memory" -a "compress"
complete -c claude-flow -n "__fish_seen_subcommand_from memory" -a "export"
complete -c claude-flow -n "__fish_seen_subcommand_from memory" -a "import"

# Hive-mind subcommands
complete -c claude-flow -n "__fish_seen_subcommand_from hive-mind hive" -a "init"
complete -c claude-flow -n "__fish_seen_subcommand_from hive-mind hive" -a "spawn"
complete -c claude-flow -n "__fish_seen_subcommand_from hive-mind hive" -a "status"
complete -c claude-flow -n "__fish_seen_subcommand_from hive-mind hive" -a "task"
complete -c claude-flow -n "__fish_seen_subcommand_from hive-mind hive" -a "join"
complete -c claude-flow -n "__fish_seen_subcommand_from hive-mind hive" -a "leave"
complete -c claude-flow -n "__fish_seen_subcommand_from hive-mind hive" -a "consensus"
complete -c claude-flow -n "__fish_seen_subcommand_from hive-mind hive" -a "broadcast"
complete -c claude-flow -n "__fish_seen_subcommand_from hive-mind hive" -a "memory"
complete -c claude-flow -n "__fish_seen_subcommand_from hive-mind hive" -a "optimize-memory"
complete -c claude-flow -n "__fish_seen_subcommand_from hive-mind hive" -a "shutdown"

# Hooks subcommands
complete -c claude-flow -n "__fish_seen_subcommand_from hooks" -a "pre-edit"
complete -c claude-flow -n "__fish_seen_subcommand_from hooks" -a "post-edit"
complete -c claude-flow -n "__fish_seen_subcommand_from hooks" -a "pre-command"
complete -c claude-flow -n "__fish_seen_subcommand_from hooks" -a "post-command"
complete -c claude-flow -n "__fish_seen_subcommand_from hooks" -a "pre-task"
complete -c claude-flow -n "__fish_seen_subcommand_from hooks" -a "post-task"
complete -c claude-flow -n "__fish_seen_subcommand_from hooks" -a "route"
complete -c claude-flow -n "__fish_seen_subcommand_from hooks" -a "explain"
complete -c claude-flow -n "__fish_seen_subcommand_from hooks" -a "pretrain"
complete -c claude-flow -n "__fish_seen_subcommand_from hooks" -a "build-agents"
complete -c claude-flow -n "__fish_seen_subcommand_from hooks" -a "metrics"
complete -c claude-flow -n "__fish_seen_subcommand_from hooks" -a "transfer"
complete -c claude-flow -n "__fish_seen_subcommand_from hooks" -a "list"
complete -c claude-flow -n "__fish_seen_subcommand_from hooks" -a "intelligence"

# Neural subcommands
complete -c claude-flow -n "__fish_seen_subcommand_from neural" -a "train status patterns predict optimize"

# Security subcommands
complete -c claude-flow -n "__fish_seen_subcommand_from security" -a "scan cve threats audit secrets"

# Performance subcommands
complete -c claude-flow -n "__fish_seen_subcommand_from performance" -a "benchmark profile metrics optimize bottleneck"

# Plugins subcommands
complete -c claude-flow -n "__fish_seen_subcommand_from plugins" -a "list install uninstall toggle info create"

# Deployment subcommands
complete -c claude-flow -n "__fish_seen_subcommand_from deployment deploy" -a "deploy status rollback history environments logs"

# Claims subcommands
complete -c claude-flow -n "__fish_seen_subcommand_from claims" -a "list check grant revoke roles policies"

# Embeddings subcommands
complete -c claude-flow -n "__fish_seen_subcommand_from embeddings" -a "generate search compare collections index providers"

# Daemon subcommands
complete -c claude-flow -n "__fish_seen_subcommand_from daemon" -a "start stop status trigger enable"

# Providers subcommands
complete -c claude-flow -n "__fish_seen_subcommand_from providers" -a "list configure test models usage"
"#;

const POWERSHELL: &str = r#"# claude-flow PowerShell completion
# Generated by claude-flow completions powershell
# Add to $PROFILE or save to a separate file and dot-source it

$script:ClaudeFlowCommands = @(
    'swarm',
    'agent',
    'task',
    'session',
    'config',
    'memory',
    'workflow',
    'hive-mind',
    'hooks',
    'daemon',
    'neural',
    'security',
    'performance',
    'providers',
    'plugins',
    'deployment',
    'claims',
    'embeddings',
    'doctor',
    'completions',
    'help',
    'version'
)

$script:SubCommands = @{
    'swarm' = @('init', 'status', 'scale', 'destroy', 'monitor', 'optimize')
    'agent' = @('spawn', 'terminate', 'status', 'list', 'pool', 'health', 'update')
    'task' = @('create', 'status', 'list', 'complete', 'cancel')
    'memory' = @('store', 'retrieve', 'search', 'list', 'delete', 'stats', 'configure', 'cleanup', 'compress', 'export', 'import')
    'hive-mind' = @('init', 'spawn', 'status', 'task', 'join', 'leave', 'consensus', 'broadcast', 'memory', 'optimize-memory', 'shutdown')
    'hive' = @('init', 'spawn', 'status', 'task', 'join', 'leave', 'consensus', 'broadcast', 'memory', 'optimize-memory', 'shutdown')
    'hooks' = @('pre-edit', 'post-edit', 'pre-command', 'post-command', 'pre-task', 'post-task', 'route', 'explain', 'pretrain', 'build-agents', 'metrics', 'transfer', 'list', 'intelligence')
    'neural' = @('train', 'status', 'patterns', 'predict', 'optimize')
    'security' = @('scan', 'cve', 'threats', 'audit', 'secrets')
    'performance' = @('benchmark', 'profile', 'metrics', 'optimize', 'bottleneck')
    'plugins' = @('list', 'install', 'uninstall', 'toggle', 'info', 'create')
    'deployment' = @('deploy', 'status', 'rollback', 'history', 'environments', 'logs')
    'deploy' = @('deploy', 'status', 'rollback', 'history', 'environments', 'logs')
    'claims' = @('list', 'check', 'grant', 'revoke', 'roles', 'policies')
    'embeddings' = @('generate', 'search', 'compare', 'collections', 'index', 'providers')
    'daemon' = @('start', 'stop', 'status', 'trigger', 'enable')
    'providers' = @('list', 'configure', 'test', 'models', 'usage')
}

Register-ArgumentCompleter -Native -CommandName claude-flow -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $tokens = $commandAst.ToString().Split(' ')
    $command = $tokens[1]

    if ($tokens.Count -eq 2) {
        # Complete top-level commands
        $script:ClaudeFlowCommands | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
    }
    elseif ($tokens.Count -eq 3 -and $script:SubCommands.ContainsKey($command)) {
        # Complete subcommands
        $script:SubCommands[$command] | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
    }
}
"#;
